/* =============================================================================
 * test_governance_axi.c  |  Version: 1.0.0
 * AI-PMC Governance FPGA Test Suite — ARM AXI Bus (Zynq)
 *
 * Compile: arm-none-eabi-gcc -mcpu=cortex-a53 -O2 -I${BSP_INCLUDE} \
 *          -o test_governance.elf test_governance_axi.c -L${BSP_LIB} -lxil
 * Run on : Zynq UltraScale+ (xczu7ev) via JTAG + Vivado SDK / Vitis
 *
 * NOTE: XPAR_ONTOLOGY_MODULE_0_S00_AXI_BASEADDR is generated by Vivado
 *       when the IP is added to the block design and a BSP is exported.
 *       If not using the IP Integrator flow, define it manually:
 *       #define XPAR_ONTOLOGY_MODULE_0_S00_AXI_BASEADDR 0x40000000
 * =============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "xil_io.h"
#include "xparameters.h"
#include "xil_cache.h"
#include "sleep.h"         /* usleep() on Zynq BSP */

/* ── AXI base address ────────────────────────────────────────────────────── */
#ifndef XPAR_ONTOLOGY_MODULE_0_S00_AXI_BASEADDR
#  error "Define XPAR_ONTOLOGY_MODULE_0_S00_AXI_BASEADDR or use Vivado IP integrator"
#endif
#define MCP_BASE  XPAR_ONTOLOGY_MODULE_0_S00_AXI_BASEADDR

/* ── Register byte offsets (matching spec/25_aipmc_rtl_spec.md §4) ───────── */
/* Core */
#define REG_STATUS          0x0000
#define REG_CONTROL         0x0004
#define REG_IRQ_ENABLE      0x0008
#define REG_AXIOM_COUNT     0x000C
#define REG_PRIME_COUNT     0x0010
#define REG_SEMANTIC_DIST   0x0014
#define REG_RUNTIME_LSW     0x0018
#define REG_RUNTIME_MSW     0x001C
#define REG_ERROR_CODE      0x002C

/* Governance config  0x1000 */
#define REG_GOV_PROFILE_ID      0x1000
#define REG_GOV_TIMEOUT_MS      0x1004
#define REG_GOV_THRESHOLDS      0x1008
#define REG_GOV_HYSTERESIS      0x100C
#define REG_GOV_ALLOWED_ACTIONS 0x1010

/* Evidence FIFO  0x2000 */
#define REG_EVIDENCE_STATUS  0x2000
#define REG_EVIDENCE_COUNT   0x2004
#define REG_EVIDENCE_ACK     0x2008
#define REG_EVIDENCE_DROPPED 0x200C

/* Governance FSM  0x3000 */
#define REG_GOV_STATE        0x3000
#define REG_GOV_FAULT_CAUSE  0x3004
#define REG_GOV_UPTIME_NS    0x3008
#define REG_GOV_PWR_UP_REQ   0x300C
#define REG_GOV_PWR_DOWN_REQ 0x3010
#define REG_GOV_THROTTLE_REQ 0x3014

/* Sequencing  0x4000 */
#define REG_SEQ_STATE       0x4000
#define REG_SEQ_CMD         0x4004
#define REG_SEQ_STEP_ID     0x4008
#define REG_SEQ_TIMEOUT_MS  0x400C
#define REG_SEQ_PGOOD       0x4010
#define REG_SEQ_EN_OUT      0x4014

/* ATP  0x5000 */
#define REG_ATP_INJECT      0x5000
#define REG_ATP_TEST_PASS   0x5004
#define REG_ATP_FAIL_REASON 0x5008
#define REG_ATP_STATUS      0x500C
#define REG_ATP_TIMEOUT_MS  0x5010

/* UPASL  0x6000 */
#define REG_THERMAL_STATUS  0x6000
#define REG_MECH_STATUS     0x6004
#define REG_EPS_STATUS      0x6008
#define REG_RAD_STATUS      0x600C
#define REG_FLUID_STATUS    0x6010
#define REG_INFO_STATUS     0x6014
#define REG_GLOBAL_HAZARD   0x6018
#define REG_STABILITY_IDX   0x601C
#define REG_UPASL_DECISION  0x6020

/* Feature Extractor  0x7000 */
#define REG_FEATURE_VEC_BASE 0x7000   /* 16 × 32-bit words */
#define REG_FEATURE_VALID    0x7040

/* ── Control / Status bits ───────────────────────────────────────────────── */
#define CTRL_START      (1u << 0)
#define CTRL_RESET      (1u << 1)
#define CTRL_CLEAR_IRQ  (1u << 2)
#define CTRL_ML_CAPTURE (1u << 3)
#define CTRL_ATP_INJECT (1u << 4)
#define CTRL_ATP_CHECK  (1u << 5)

#define STATUS_BUSY     (1u << 0)
#define STATUS_DONE     (1u << 1)
#define STATUS_ERROR    (1u << 2)

#define GOV_IDLE        1u
#define GOV_POWERUP     2u
#define GOV_RUN         3u
#define GOV_POWEROFF    4u
#define GOV_FAULT       5u
#define GOV_SAFE        6u

#define SEQ_DONE        4u
#define SEQ_FAIL        5u

#define UPASL_REFUSE    0u
#define UPASL_LIMIT     1u
#define UPASL_ALLOW     2u

/* UPASL domain status 3-bit encoding */
#define DOMAIN_SAT      1u
#define DOMAIN_VIOL     2u
#define DOMAIN_UND      4u

/* ATP test IDs */
#define ATP_VIN_INVALID    1u
#define ATP_PGOOD_TIMEOUT  2u

/* ── AXI helpers ─────────────────────────────────────────────────────────── */
static inline void axi_write(uint32_t off, uint32_t val) {
    Xil_Out32(MCP_BASE + off, val);
    __asm__ volatile ("dsb sy" ::: "memory");
}

static inline uint32_t axi_read(uint32_t off) {
    __asm__ volatile ("dsb sy" ::: "memory");
    return Xil_In32(MCP_BASE + off);
}

/* ── Test result tracking ────────────────────────────────────────────────── */
#define MAX_TESTS 64

typedef struct {
    const char *name;
    int         passed;
    uint32_t    value;      /* last read value for diagnostics */
} TestResult;

static TestResult results[MAX_TESTS];
static int        test_count  = 0;
static int        pass_count  = 0;
static int        fail_count  = 0;

static void test_assert(const char *name, int cond, uint32_t val) {
    if (test_count >= MAX_TESTS) return;
    results[test_count].name   = name;
    results[test_count].passed = cond;
    results[test_count].value  = val;
    test_count++;
    if (cond) {
        printf("  [PASS] %s\n", name);
        pass_count++;
    } else {
        printf("  [FAIL] %s  (val=0x%08X)\n", name, (unsigned)val);
        fail_count++;
    }
}

/* Poll for condition with microsecond timeout; returns 1 if condition met */
static int poll_until(uint32_t off, uint32_t mask, uint32_t expected,
                      uint32_t timeout_us) {
    uint32_t elapsed = 0;
    while (elapsed < timeout_us) {
        if ((axi_read(off) & mask) == expected) return 1;
        usleep(100);
        elapsed += 100;
    }
    return 0;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-01 — AXI Register Access                                           */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_axi_register_access(void) {
    uint32_t v;
    printf("\n[M-01] AXI Register Access\n");

    /* Sanity: write timeout config and read back */
    axi_write(REG_GOV_TIMEOUT_MS, 0xA5A5A5A5u);
    v = axi_read(REG_GOV_TIMEOUT_MS);
    test_assert("M-01: Write / read-back round-trip", v == 0xA5A5A5A5u, v);
    /* Restore */
    axi_write(REG_GOV_TIMEOUT_MS, 1000u);

    /* All key registers respond (not 0xFFFFFFFF = unresponsive bus) */
    const uint32_t probe_regs[] = {
        REG_STATUS, REG_CONTROL, REG_GOV_STATE,
        REG_SEQ_STATE, REG_ATP_TEST_PASS,
        REG_THERMAL_STATUS, REG_UPASL_DECISION
    };
    int ok = 1;
    for (int i = 0; i < (int)(sizeof(probe_regs)/sizeof(probe_regs[0])); i++) {
        if (axi_read(probe_regs[i]) == 0xFFFFFFFFu) { ok = 0; break; }
    }
    test_assert("M-01: All key registers accessible", ok, ok ? 1 : 0);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-02 — Governance Config                                              */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_governance_config(void) {
    uint32_t v;
    printf("\n[M-02] Governance Configuration\n");

    axi_write(REG_GOV_PROFILE_ID, 1u);
    v = axi_read(REG_GOV_PROFILE_ID);
    test_assert("M-02: Profile ID write/read", v == 1u, v);

    axi_write(REG_GOV_TIMEOUT_MS, 100u);
    v = axi_read(REG_GOV_TIMEOUT_MS);
    test_assert("M-02: Timeout 100 ms", v == 100u, v);

    /* [23:12]=temp_max × 10 = 850, [11:0]=vcap_min_mV = 800 */
    uint32_t thresh = (850u << 12) | 800u;
    axi_write(REG_GOV_THRESHOLDS, thresh);
    v = axi_read(REG_GOV_THRESHOLDS);
    test_assert("M-02: Thresholds config", v == thresh, v);

    axi_write(REG_GOV_ALLOWED_ACTIONS, 0x03u);
    v = axi_read(REG_GOV_ALLOWED_ACTIONS);
    test_assert("M-02: Allowed actions", v == 0x03u, v);

    /* Restore defaults */
    axi_write(REG_GOV_THRESHOLDS, 0u);
    axi_write(REG_GOV_TIMEOUT_MS, 1000u);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-03 — Evidence FIFO                                                 */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_evidence_fifo(void) {
    uint32_t count, v;
    printf("\n[M-03] Evidence FIFO\n");

    /* BOOT event should already be in FIFO */
    count = axi_read(REG_EVIDENCE_COUNT);
    test_assert("M-03: FIFO non-empty after boot", count > 0u, count);

    /* Read and acknowledge records */
    uint32_t read = 0;
    while (axi_read(REG_EVIDENCE_COUNT) > 0 && read < 16u) {
        (void)axi_read(REG_EVIDENCE_STATUS);     /* pop */
        axi_write(REG_EVIDENCE_ACK, 1u);
        read++;
    }
    test_assert("M-03: FIFO read/ack (read > 0)", read > 0, read);

    v = axi_read(REG_EVIDENCE_DROPPED);
    test_assert("M-03: No evidence drops", v == 0u, v);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-04 — Governance FSM                                                */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_governance_fsm(void) {
    uint32_t state, fault;
    printf("\n[M-04] Governance FSM\n");

    /* Reset */
    axi_write(REG_CONTROL, CTRL_RESET);
    usleep(10000);

    state = axi_read(REG_GOV_STATE);
    test_assert("M-04: After reset → IDLE (state<=1)", state <= 1u, state);

    /* Request power-up */
    axi_write(REG_GOV_PWR_UP_REQ, 1u);
    usleep(50000);
    state = axi_read(REG_GOV_STATE);
    test_assert("M-04: After pup_req → POWERUP or RUN",
                state == GOV_POWERUP || state == GOV_RUN, state);

    fault = axi_read(REG_GOV_FAULT_CAUSE);
    test_assert("M-04: Fault cause readable (not 0xFF…)", fault != 0xFFFFFFFFu, fault);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-05 — Sequencing Engine                                              */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_sequencing_engine(void) {
    uint32_t v;
    printf("\n[M-05] Sequencing Engine\n");

    axi_write(REG_CONTROL, CTRL_RESET);
    usleep(10000);

    axi_write(REG_SEQ_TIMEOUT_MS, 50u);
    v = axi_read(REG_SEQ_TIMEOUT_MS);
    test_assert("M-05: Timeout config 50 ms", v == 50u, v);

    axi_write(REG_SEQ_CMD, 1u);   /* START */
    usleep(10000);
    v = axi_read(REG_SEQ_STATE);
    test_assert("M-05: Sequencing started (RUN=2 or START=1)",
                v == 1u || v == 2u, v);

    v = axi_read(REG_SEQ_STEP_ID);
    test_assert("M-05: Step ID readable", v != 0xFFFFFFFFu, v);

    /* Hold / Resume */
    axi_write(REG_SEQ_CMD, 4u);   /* HOLD [bit2] */
    usleep(10000);
    v = axi_read(REG_SEQ_STATE);
    test_assert("M-05: HOLD state (state==3)", v == 3u, v);

    axi_write(REG_SEQ_CMD, 8u);   /* RESUME [bit3] */
    usleep(10000);
    v = axi_read(REG_SEQ_STATE);
    test_assert("M-05: Resume → RUN (state==2)", v == 2u, v);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-06 — ATP-01 VIN invalid blocks power-up                            */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_atp01_vin_invalid(void) {
    uint32_t pass, reason;
    printf("\n[M-06] ATP-01 VIN Invalid\n");

    axi_write(REG_ATP_INJECT, ATP_VIN_INVALID);
    /* Wait ≥ dwell: 4096 clk @ 100 MHz = 40.96 µs; add margin */
    usleep(200000);

    pass   = axi_read(REG_ATP_TEST_PASS);
    reason = axi_read(REG_ATP_FAIL_REASON);
    test_assert("M-06: ATP-01 VIN invalid → pass==1", pass == 1u, pass);
    if (!pass) printf("    fail_reason=0x%X\n", (unsigned)reason);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-07 — ATP-02 PGOOD timeout → ABORT                                 */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_atp02_pgood_timeout(void) {
    uint32_t pass;
    printf("\n[M-07] ATP-02 PGOOD Timeout\n");

    axi_write(REG_ATP_INJECT, ATP_PGOOD_TIMEOUT);
    usleep(200000);

    pass = axi_read(REG_ATP_TEST_PASS);
    test_assert("M-07: ATP-02 PGOOD timeout → pass==1", pass == 1u, pass);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: M-08 — Feature Extractor                                              */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_feature_extractor(void) {
    uint32_t words[16];
    int      all_zero = 1;
    printf("\n[M-08] Feature Extractor\n");

    axi_write(REG_CONTROL, CTRL_ML_CAPTURE);
    usleep(5000);

    for (int i = 0; i < 16; i++) {
        words[i] = axi_read(REG_FEATURE_VEC_BASE + i * 4u);
        if (words[i] != 0u) all_zero = 0;
    }
    test_assert("M-08: Feature vector captured (non-zero)", !all_zero, all_zero ? 0u : 1u);
    test_assert("M-08: Feature vector is 64 bytes",
                sizeof(words) == 64u, (uint32_t)sizeof(words));
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* TEST: UPASL Domain Engine                                                   */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_upasl_domains(void) {
    uint32_t v;
    printf("\n[UPASL] Domain Engine\n");

    /* Individual domain statuses (each 3-bit: SAT=1, VIOL=2, UND=4) */
    const uint32_t domain_regs[] = {
        REG_THERMAL_STATUS, REG_MECH_STATUS, REG_EPS_STATUS,
        REG_RAD_STATUS, REG_FLUID_STATUS, REG_INFO_STATUS
    };
    const char *domain_names[] = {
        "Thermal","Mechanical","EPS","Radiation","Fluid","Information"
    };
    for (int i = 0; i < 6; i++) {
        v = axi_read(domain_regs[i]) & 0x7u;  /* 3-bit field */
        /* SAT(1), VIOL(2), UND(4) — any of the three is valid */
        char buf[64];
        snprintf(buf, sizeof(buf), "UPASL: %s domain status valid (1|2|4)",
                 domain_names[i]);
        test_assert(buf, v == DOMAIN_SAT || v == DOMAIN_VIOL || v == DOMAIN_UND, v);
    }

    v = axi_read(REG_GLOBAL_HAZARD);
    test_assert("UPASL: Hazard in range [0,65535]", v <= 0xFFFFu, v);

    v = axi_read(REG_STABILITY_IDX);
    test_assert("UPASL: Stability in range [0,65535]", v <= 0xFFFFu, v);

    v = axi_read(REG_UPASL_DECISION) & 0x3u;
    test_assert("UPASL: Decision is ALLOW/LIMIT/REFUSE (0-2)", v <= 2u, v);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* PERF TEST: AXI read latency                                                 */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_performance_latency(void) {
    printf("\n[PERF] AXI Latency\n");
    /* On Zynq, Xil_In32 + dsb ≈ 10–100 cycles depending on AXI fabric
       We measure by reading 1000 times and comparing before/after timer */
    XTime t0, t1;
    XTime_GetTime(&t0);
    volatile uint32_t dummy = 0;
    for (int i = 0; i < 1000; i++) dummy ^= axi_read(REG_STATUS);
    XTime_GetTime(&t1);
    (void)dummy;

    /* XTime ticks at COUNTS_PER_SECOND */
    uint64_t elapsed_ns = (uint64_t)(t1 - t0) * 1000000000ULL / COUNTS_PER_SECOND;
    uint32_t avg_ns = (uint32_t)(elapsed_ns / 1000u);
    printf("  AXI read avg latency: %u ns over 1000 reads\n", avg_ns);
    test_assert("PERF: Avg AXI read latency < 1000 ns", avg_ns < 1000u, avg_ns);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* STRESS TEST: Continuous operation                                           */
/* ─────────────────────────────────────────────────────────────────────────── */
static void test_stress_continuous(void) {
    printf("\n[STRESS] 1000-iteration continuous test\n");
    int errors = 0;

    for (int i = 0; i < 1000; i++) {
        axi_write(REG_CONTROL, CTRL_RESET);
        usleep(50);
        axi_write(REG_GOV_PWR_UP_REQ, 1u);
        usleep(50);

        uint32_t state = axi_read(REG_GOV_STATE);
        if (state > 6u) errors++;

        uint32_t count = axi_read(REG_EVIDENCE_COUNT);
        if (count > 1024u) errors++;  /* FIFO depth exceeded */
    }
    test_assert("STRESS: 1 000 cycles, no state/FIFO errors", errors == 0, errors);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* MAIN                                                                        */
/* ─────────────────────────────────────────────────────────────────────────── */
int main(void) {
    Xil_DCacheEnable();
    Xil_ICacheEnable();

    printf("\n========================================\n");
    printf("AI-PMC Governance FPGA Test Suite (ARM)\n");
    printf("========================================\n");

    /* Verify FPGA is on the bus */
    uint32_t probe = axi_read(REG_STATUS);
    if (probe == 0xFFFFFFFFu) {
        printf("ERROR: FPGA not responding (STATUS == 0xFFFFFFFF). "
               "Check AXI connection and bitstream.\n");
        return -1;
    }
    printf("FPGA detected (STATUS=0x%08X). Running %d test groups...\n\n",
           (unsigned)probe, 10);

    test_axi_register_access();
    test_governance_config();
    test_evidence_fifo();
    test_governance_fsm();
    test_sequencing_engine();
    test_atp01_vin_invalid();
    test_atp02_pgood_timeout();
    test_feature_extractor();
    test_upasl_domains();
    test_performance_latency();
    test_stress_continuous();

    printf("\n========================================\n");
    printf("FINAL: %d PASS  /  %d FAIL  /  %d TOTAL\n",
           pass_count, fail_count, test_count);
    printf("========================================\n");

    return (fail_count == 0) ? 0 : -1;
}
